### ISSUE TITLE
Does FileVault 2 work with this setup?

### ISSUE THREAD

**Issue by DaveFlowberries** [kcunanan/Jared-PC#2]
Just curious if you tested it, since I tried before and it locked me out of the system.

**Comment by deeplyfriedchicken** [comment]
Hi @DaveFlowberries sorry I missed this, I haven't tested FileVault unfortunately, but I'll look into it when I get that chance!

**Comment by DaveFlowberries** [comment]
> Hi @DaveFlowberries sorry I missed this, I haven't tested FileVault unfortunately, but I'll look into it when I get that chance!

No worries. I just wanted to report back that I got it to work. But firstly, I am using the Clover config files from another repo by user bydavy, so I am not sure if the following info applies to your setup as well.

Basically you just need the correct drivers in drivers64UEFI folder, and need to have the latest version of Clover installed. When I update clover I also update the following files as well as it caused an issue before when I didn't.

They can be found in the EFI/CLOVER/drivers-Off/drivers64UEFI/FileVault2
Located here https://sourceforge.net/projects/cloverefiboot/files/Bootable_ISO/

Make sure you don't have "preboot" excluded from "GUI" "Hide Volume" in clover config, otherwise you won't see the new FileVault boot option.

Hope that helps someone!
